spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/final-project
    username: postgres
    password: louis14
  jpa:
    hibernate:
      ddlauto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static
  config:
    activate:
      on-profile: dev